#!/bin/bash

set -e

BASEDIR="$( cd "$( dirname "$( realpath "${BASH_SOURCE[0]}" )" )/.." >/dev/null 2>&1 && pwd )"

get_sys_deps() {
    ldd ${1} 2>/dev/null|grep 'ld-linux-x86-64'|awk '{print $1}'|sort|uniq
    ldd ${1} 2>/dev/null|grep 'x86_64-linux-gnu'|awk '{print $3}'|sort|uniq
}

echo "Require sudo privileges:"
sudo -l > /dev/null

sudo which chroot >/dev/null
if [ $? -ne 0 ]; then
    echo "chroot is required, exiting"
    exit 1
fi

cd ${BASEDIR}
sudo rm -rf .build
mkdir .build

sudo mkdir -p .build/{bin,dev,etc,proc,sbin,sys,tmp,usr/{bin,sbin},var/run}

sudo mknod -m 0600 .build/dev/console c 5 1
sudo mknod -m 0666 .build/dev/null c 1 3
sudo mknod -m 0666 .build/dev/tty c 5 0
sudo mknod -m 0666 .build/dev/zero c 1 5

sudo cp /bin/busybox .build/bin/.
for dep in $(get_sys_deps /bin/busybox); do
    sudo install -D ${dep} .build/${dep}
done

sudo chroot .build /bin/busybox --install -s

tar -C .build -czf packages/busybox-root.tar.gz .
sudo rm -rf .build
